create table if not exists clera_sessions(id text primary key,data jsonb not null,expires_at timestamptz not null default now()+interval '1 day');
alter table clera_sessions enable row level security;
alter table clera_sessions force row level security;
drop policy if exists clera_scope on clera_sessions;
create policy clera_scope on clera_sessions using(id=current_setting('clera.session',true)) with check(id=current_setting('clera.session',true));
create table if not exists clera_proposals(id uuid primary key,owner text not null references clera_sessions(id) on delete cascade,data jsonb not null,expires_at timestamptz not null);
create index if not exists clera_proposals_owner on clera_proposals(owner);
alter table clera_proposals enable row level security;
alter table clera_proposals force row level security;
drop policy if exists clera_proposal_scope on clera_proposals;
create policy clera_proposal_scope on clera_proposals using(owner=current_setting('clera.session',true)) with check(owner=current_setting('clera.session',true));
create table if not exists clera_ai_usage(day date primary key,attempts integer not null check(attempts>=0));
alter table clera_ai_usage enable row level security;
create table if not exists clera_patient_invites(token_hash text primary key,owner text not null references clera_sessions(id) on delete cascade,patient_id text not null,expires_at timestamptz not null default now()+interval '10 minutes');
alter table clera_patient_invites enable row level security;
create table if not exists clera_patient_sessions(token_hash text primary key,owner text not null references clera_sessions(id) on delete cascade,patient_id text not null,expires_at timestamptz not null default now()+interval '30 minutes');
alter table clera_patient_sessions enable row level security;
create index if not exists clera_patient_sessions_owner on clera_patient_sessions(owner);
create table if not exists clera_help_requests(id uuid primary key,owner text not null references clera_sessions(id) on delete cascade,visit_id uuid not null,category text not null check(category in ('paperwork','accessibility','appointment','general')),step text not null check(step in ('welcome','find','confirm','done')),created_at timestamptz not null default now(),resolved_at timestamptz);
create unique index if not exists clera_help_one_open_visit on clera_help_requests(owner,visit_id) where resolved_at is null;
alter table clera_help_requests enable row level security;
alter table clera_help_requests force row level security;
drop policy if exists clera_help_scope on clera_help_requests;
create policy clera_help_scope on clera_help_requests using(owner=current_setting('clera.session',true)) with check(owner=current_setting('clera.session',true));
